### ISSUE TITLE
Adding a Show instance

### ISSUE THREAD

**Issue by theobat** [nikita-volkov/hasql-dynamic-statements#1]
Would it be possible to add a show instance to Snippet ? (I can create a PR if you agree with the idea) . A simple newtype-deriving should be fine...

**Comment by nikita-volkov** [comment]
Sorry. Wasn't watching this repository for some reason.

Yes. I'll accept the PR.

**Comment by theobat** [comment]
Is there absolutely no way to show the value encoded in an Encoders/Value ? Because I'd like, if possible, not to show placeholders for the query's arguments but their actual value especially for the Eq typeclass. I don't understand how to do that, it seems the only possible operation on an Encoder is to "consume" stuff. Can you confirm what I'm trying to do is impossible ?

**Comment by nikita-volkov** [comment]
Encoders produce binary data. They have no logic related to rendering to readable SQL values.

**Comment by theobat** [comment]
So, I needed this for exploration and tests, but I managed to simply use parametric polymorphism on my assembling functions (the data "holder" of my dynamic queries is now polymorphic, which enables me to use the same logic but with Text && show instead of Snippet and param in a test environment).

Thanks anyway.
