### ISSUE TITLE
Expose "sql" function to construct Snippet from ByteString

### ISSUE THREAD

**Issue by steve-chavez** [nikita-volkov/hasql-dynamic-statements#4]
I've noted that there's an unexposed function:
https://github.com/nikita-volkov/hasql-dynamic-statements/blob/524d790a4594936ae262ab38bf90335139367ed8/library/Hasql/DynamicStatements/Snippet/Defs.hs#L43-L47

Would it be possible to export it?

### Context

I'm trying to convert PostgREST to use hasql-dynamic-statements. Until now, we've been concatenating Text fragments to produce our queries.

There are many functions like this [one](https://github.com/PostgREST/postgrest/blob/99ecc7af70e36ed8a52919dd258e19e6aaa834e3/src/PostgREST/QueryBuilder.hs#L191-L193), who use the [intercalate](https://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html#v:intercalate) function.
I'm unable to convert them to use `Snippet`. For example I'm trying this:

```haskell
setLocalSearchPathQuery :: [BS.ByteString] -> Snippet
setLocalSearchPathQuery vals =
  "SET LOCAL search_path = " <> x <> ";"
  where
    x = BS.intercalate ", " vals

-- which doesn't compile
-- src/PostgREST/QueryBuilder.hs:195:3: error:
--    • Couldn't match expected type ‘Snippet’
--                  with actual type ‘ByteString’
```

I believe the `sql` function would help me there. Or perhaps you have another suggestion?

**Comment by nikita-volkov** [comment]
At first I wondered why you didn't use `param`, but it seems like this kind of query is unparameterizable.

I've just made a release exposing the function.
